server:
  port: 5300

spring:
  boot:
    admin:
      discovery:
        converter:
          management-context-path: /actuator  

management:
  endpoints:
    web:
      exposure:
        include: '*'
