spring:
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:postgresql://localhost:5432/odpdb
    username: odpuser
    password: changeme
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  language: bg,es,cs,da,de,et,el,en,fr,ga,hr,it,lv,lt,hu,mt,nl,pl,pt,ro,sk,sl,fi,sv
  path:
    front: https://nyiwpht1kf.execute-api.eu-west-1.amazonaws.com/sitefront
    eurovoc: http://eurovoc.europa.eu/
    redmap:
      reference: http://www.redmapl3.europarl.europa.eu/RedmapFront/Redmap/reference
      eurovoc: http://www.redmapl3.europarl.europa.eu/RedmapFront/Redmap/concept/reds:Concept_Eurovoc
  elasticsearch:
    path: localhost:9200
    user: odpdomadmin
    password: N4xfjCvqrP+7K2kgv
    protocol: http
aws:
  s3:
    region: eu-west-1
    bucketName: odp-admin-bucket
    store:
      avatar: avatar
      resource: resource
      frontUser: frontUser
      sitemap: sitemap