spring:
  datasource:
    sql-script-encoding: UTF-8
    url: jdbc:postgresql://localhost:5432/odpdb
    username: odpuser
    password: changeme
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    
application:
  path:
    front: http://odp-appe-j99ig9jt823p.eba-pgcyydbs.eu-west-1.elasticbeanstalk.com
    eurovoc: http://eurovoc.europa.eu/
    redmap:
      reference: http://www.redmapl3.europarl.europa.eu/RedmapFront/Redmap/reference
      eurovoc: http://www.redmapl3.europarl.europa.eu/RedmapFront/Redmap/concept/reds:Concept_Eurovoc
  elasticsearch:
    path: localhost:9200
    user: odpdomadmin
    password: N4xfjCvqrP+7K2kgv
    protocol: http
aws:
    s3:
        region: eu-west-1
        bucketName: odp-admin-bucket
        store:
            avatar: avatar
            resource: resource
            frontUser: frontUser
            sitemap: sitemap
