spring:
  devtools:
    livereload:
      port: 35730
  cloud:
    loadbalancer:
       ribbon:
         enabled: false
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/
server:
  port: 9102
