spring:
  devtools:
    livereload:
      port: 35730
  cloud:
    loadbalancer:
       ribbon:
         enabled: false
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://ip-10-103-13-145.eu-west-1.compute.internal/edgeeureka/eureka/
server:
  port: 5100
