spring:
  devtools:
    livereload:
      port: 35730
  cloud:
    loadbalancer:
       ribbon:
         enabled: false
eureka:
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://awseb-AWSEB-C5YO7RRI7F8Z-359842224.eu-west-1.elb.amazonaws.com/edgeeureka/eureka/
server:
  port: 5100
