eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/
server:
  port: 9004
  
logging:
  level:
    org.springframework: TRACE
  
spring:
  cloud:
    gateway:
      routes:
      - id: microservice-user
        uri: lb://MICROSERVICE-USER
        predicates:
          - Path=/Users/**,Path=/Roles/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - '*'
