eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/
server:
  port: 9004
  
spring:
  cloud:
    gateway:
      routes:
      - id: microservice-user
        uri: http://localhost:9102
        predicates:
        - Path=/**
        
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - '*'
