eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/
server:
  port: 9004
  
logging:
  level:
    org.springframework: TRACE
  
spring:
  cloud:
    gateway:
      routes:
      - id: microservice-user
        uri: lb://MICROSERVICE-USER
        predicates:
          - Path=/Users/**
      - id: microservice-roles
        uri: lb://MICROSERVICE-ROLES
        predicates:
          - Path=/Roles/**
      - id: microservice-user-role
        uri: lb://MICROSERVICE-USER-ROLE
        predicates:
          - Path=/UserRoles/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers"
            allowCredentials: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - '*'
