eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5100/edgeeureka/eureka/
server:
  port: 5000
  
logging:
  level:
    org.springframework: INFO
  
spring:
  cloud:
    gateway:
      routes:
        - id: microservice-odp
          uri: lb://MICROSERVICE-ODP
          predicates:
            - Path=/OdpDatasetService/**, /UserService/**, /ReuseService/**, /UserSiteService/**, /RedmapService/**, /redmap/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - '*'
