eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/
server:
  port: 9004
  
logging:
  level:
    org.springframework: TRACE
  
spring:
  cloud:
    gateway:
      routes:
        - id: microservice-odp-aws
          uri: lb://MICROSERVICE-ODP-AWS
          predicates:
            - Path=/OdpDatasetService/**, /UserService/**, /RedmapService/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - '*'
