eureka:
  client:
    serviceUrl:
      defaultZone: http://awseb-AWSEB-NKRHE4WJ2R7G-1662464568.eu-west-1.elb.amazonaws.com/edgeeureka/eureka/
server:
  port: 5000
  
logging:
  level:
    org.springframework: INFO
  
spring:
  cloud:
    gateway:
      routes:
        - id: microservice-odp-aws
          uri: lb://MICROSERVICE-ODP-AWS
          predicates:
            - Path=/OdpDatasetService/**, /UserService/**, /RedmapService/**, /redmap/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - '*'
