spring:
  datasource:
    sql-script-encoding: UTF-8
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

application:
  path:
    redmap:
      reference: http://www.redmapl3.europarl.europa.eu/RedmapFront/Redmap/reference
