eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/

spring:
  datasource:
    sql-script-encoding: UTF-8
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect

application:
  path:
    redmap:
      reference: http://www.redmapl3.europarl.europa.eu/RedmapFront/Redmap/reference
      eurovoc: http://www.redmapl3.europarl.europa.eu/RedmapFront/Redmap/concept/reds:Concept_Eurovoc
      