eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/

spring:
  datasource:
    sql-script-encoding: UTF-8
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect

application:
  path:
    to:
      store: /Users/sergecalmant/dev/nginx/storage/avatar
      delivery: http://localhost:8080/storage/avatar